<?php include('componentes/herosobre.php') ?>
<?php include('componentes/textsobre.php') ?>
<?php include('componentes/textbgsobre.php') ?>
<?php include('componentes/double-roxosobre.php') ?>
<?php include('componentes/roxosobre.php') ?>
<?php include('componentes/richardjafez.php') ?>
<?php include('componentes/cardverdesobre.php') ?>
<?php include('componentes/depoimentos-cliente-sobre.php') ?>
<?php include('componentes/squadssobre.php') ?>
<?php include('componentes/depoimentos-colaborador-sobre.php') ?>
<?php include('componentes/cases-ctacontato.php') ?>